function s = saveobj(obj)
    
    import DebuggerKit.Debugger.printDebugMessage
    import UtilityKit.Utilities.toolbox.*

    propertyNames   = {...
        'data',...
        'HardwareConfiguration',...
        'gearType',...
        'cruise',...
        'gear',...
        'station',...
        'areaId',...
        'longitude',...
        'latitude',...
        'depth',...
        'timeDeployment',...
        'timeRecovery',...
        'timeOfInterestStart',...
        'timeOfInterestEnd',...
        'calibration',...
        'analysis',...
        'dataFolderInfo',...
        'dataVersion',...
        'SaveFile',...
        'LoadFile'...
        };
    
    nProperties     = numel(propertyNames);
    s = struct();
    for pp = 1:nProperties
        printDebugMessage('Verbose','gearDeployment: Saving property %u of %u: ''%s''...',pp,nProperties,propertyNames{pp})
        
        s.(propertyNames{pp}) = obj.(propertyNames{pp});
    end
    
    % Properties only stored in the saved struct, not the gearDeployment instance
    s.saveDate              = datetime('now');
    s.toolboxVersion        = toolbox.version('Dingi');
    s.DataStructureVersion  = obj.DataStructureVersion;
end
