function timeSlow = getTimeSlow(obj)
    structureId   	= 17;
    timeSlowRaw  	= [obj.getDataArray(structureId,4,'uint8'),...
                       obj.getDataArray(structureId,5,'uint8'),...
                       obj.getDataArray(structureId,6,'uint8'),...
                       obj.getDataArray(structureId,7,'uint8'),...
                       obj.getDataArray(structureId,8,'uint8'),...
                       obj.getDataArray(structureId,9,'uint8')];
	% scale temperature
    timeSlow       	= ECToolbox.BCD2datetime(timeSlowRaw);
end