function initializeZoomAxis(obj)


    obj.ZoomAxis = axes(obj.FigureHandle,...
        'Visible',                  'on',...
        'NextPlot',                 'add',...
        'Tag',                      'ZoomAxis',...
        'Units',                    obj.Units,...
        'Position',                 [obj.OuterMargin,obj.OuterMargin,obj.AxesCanvas(3),obj.FooterHeight],...
        'FontName',                 obj.FontName,...
        'FontSize',                 obj.FontSize,...
        'LabelFontSizeMultiplier',  obj.FontSizeLabelMultiplier,...
        'TitleFontSizeMultiplier',  obj.FontSizeTitleMultiplier,...
        'TickDir',                  'out',...
        'TickLength',               ones(1,2).*obj.TickLength./max(obj.AxesCanvas(3:4)),...
        'ColorOrder',               cbrewer('qual','Set1',9),...
        'YColor',                   'none');
end