function updateVariableAxes(obj)
    
    % Calculate axes height
    axesHeight          = (obj.AxesCanvas(4) - (obj.NSelectedVariables - 1)*obj.InnerMargin)/obj.NSelectedVariables;
    
    % Calculate axes positions
    obj.AxesPosition	= [...
        obj.AxesCanvas(1).*ones(obj.NSelectedVariables,1),...
        obj.AxesCanvas(2) + ((1:obj.NSelectedVariables)' - 1)*(axesHeight + obj.InnerMargin),...
        obj.AxesCanvas(3).*ones(obj.NSelectedVariables,1),...
        axesHeight.*ones(obj.NSelectedVariables,1)];
    
    % Set the positions and make axes visible
    set(obj.AxesHandles(obj.VariableIsSelected),...
        {'Position'},     num2cell(obj.AxesPosition,2),...
        {'Visible'},      {'on'})
    
    % Make all other axes invisible
    set(obj.AxesHandles(~obj.VariableIsSelected),...
        {'Visible'},      {'off'})
end