function varargout = plot(obj,varargin)

    [...
        figureProperties,...
        axesProperties ...
    ] = parseInputs(varargin{:});

    
    switch class(obj)
        case 'AnalysisKit.bigoFluxAnalysis'
            figNums = 40;
        otherwise
            figNums = 20;
    end
    
    fig     = figNums(1);
    hfig    = figure(fig);
    clf

    set(hfig,figureProperties{:})
    
    varargout = {...
        hfig,...
        axesProperties};
end

function varargout = parseInputs(varargin)

    import GraphKit.getMaxFigureSize
    import GraphKit.Colormaps.cm
    
    % Define default values
    maxFigureSize	= getMaxFigureSize;
    paperHeight   	= maxFigureSize(2);
    paperWidth  	= paperHeight/2;
    paperPos       	= [paperWidth paperHeight];

    cMap            = cm('Set1',7);

    defaultFigureProperties = {...
        'Visible',              'on',...
        'Name',                 'Analysis',...
        'Menubar',              'figure',...
        'Toolbar',              'auto',...
        'PaperSize',            paperPos,...
        'PaperOrientation',     'Portrait',...
        'Units',                'normalized',...
        'Position',             [0.5 0 0.5 1]};
    defaultAxesProperties = {...
        'NextPlot',                 'add',...
        'XColor',                   'k',...
        'YColor',                   'k',...
        'FontSize',                 12,...
        'TitleFontSizeMultiplier',  1,...
        'LabelFontSizeMultiplier',  1,...
        'TitleFontWeight',          'normal',...
        'Box',                      'on',...
        'ColorOrder',               cMap};

    % Create input parser
    p = inputParser;
    addParameter(p,'FigureProperties',defaultFigureProperties)
    addParameter(p,'AxesProperties',defaultAxesProperties)
    
    parse(p,varargin{:})

    figureProperties   	= p.Results.FigureProperties;
    axesProperties   	= p.Results.AxesProperties;
    
    varargout   = {...
        figureProperties,...
        axesProperties};
              
    % sanity check
	if numel(fieldnames(p.Results)) ~= numel(varargout)
        error('Dingi:AnalysisKit:analysis:plot:parseInputs:invalidNumberOfOutputs',...
          'Parsed variable number mismatches the output.')
	end
end
