classdef ndigits_test < matlab.unittest.TestCase
    
    % run:
    % tests = matlab.unittest.TestSuite.fromClass(?Tests.DataKit.ndigits_test);
    % run(tests)
    
    properties
        
    end
    properties (MethodSetupParameter)
        
    end
    properties (TestParameter)
        Number 	= struct(...
                             ... %
                             'D1PS',    struct('Num',       5,...
                                               'Exp',       1),...
                             'D1PM',    struct('Num',       353,...
                                               'Exp',       3),...
                             'D1PL',    struct('Num',       3.334e5,...
                                               'Exp',       6),...
                             'D1PXL',   struct('Num',       3.334e100,...
                                               'Exp',       101),...
                             'D1NS',    struct('Num',       -5,...
                                               'Exp',       1),...
                             'D1NM',    struct('Num',       -353,...
                                               'Exp',       3),...
                             'D1NL',    struct('Num',       -3.334e5,...
                                               'Exp',       6),...
                             'D1NXL',   struct('Num',       -3.334e100,...
                                               'Exp',       101),...
                             'zero',    struct('Num',       0,...
                                               'Exp',       1),...
                             'P10PS',   struct('Num',       1,...
                                               'Exp',       1),...
                             'P10PM',   struct('Num',       100,...
                                               'Exp',       3),...
                             'P10PL',   struct('Num',       1e6,...
                                               'Exp',       7),...
                             'P10PXL',  struct('Num',       1e100,...
                                               'Exp',       101),...
                             'P10NS',   struct('Num',       -1,...
                                               'Exp',       1),...
                             'P10NM',   struct('Num',       -100,...
                                               'Exp',       3),...
                             'P10NL',   struct('Num',       -1e6,...
                                               'Exp',       7),...
                             'P10NXL',  struct('Num',       -1e100,...
                                               'Exp',       101)...
                            )
    end
    
    methods (TestClassSetup)
        function addPath(testCase)
            pathOld = path;
            testCase.addTeardown(@path,pathOld)
            addpath('/Users/David/Dropbox/David/Syncing/MATLAB/toolboxes/')
        end
    end
    methods (TestMethodSetup)
        
    end
    methods (TestMethodTeardown)
        
    end
    
    methods (Test)
        function testShape(testCase,Number)
            
            % Subtest 01: verify output shapes are equal
            actual      = DataKit.ndigits(Number.Num);
            expected	= Number.Exp;
            testCase.verifyEqual(actual,expected);
        end
	end
end