function gd = generateSampleGearDeployments()
% generateSampleGearDeployments  Generates sample subclass instances
%   GENERATESAMPLEGEARDEPLOYMENTS Generates instances of all 
%   GearKit.gearDeployment subclass filled with sample data
%
%   Syntax
%     gd = generateSampleGearDeployments()
%
%   Description
%     gd = generateSampleGearDeployments() generates instances of all 
%   	GearKit.gearDeployment subclass filled with sample data
%
%   Example(s)
%     gd = generateSampleGearDeployments() returns a struct with a field
%       name for each subclass of GearKit.gearDeployment of which each
%       contains an array of subclass instance handles.
%
%
%   Input Arguments
%
%
%   Output Arguments
%     gd - sample gearDeployments subclasses
%       struct
%         A struct with a field name for each subclass of
%         GearKit.gearDeployment of which each contains an array of
%         subclass instance handles.
%
%
%   Name-Value Pair Arguments
%
%
%   See also
%
%   Copyright (c) 2022 David Clemens (dclemens@geomar.de)
%

    dataPools   = generateDataPools();
    nDataPools  = numel(dataPools);
    
    infoDingi   = what('Dingi');
   	pathDingi   = infoDingi.path;
    subclasses  = getSubclasses('GearKit.gearDeployment',[pathDingi,'/GearKit']);
    nSubclasses = numel(subclasses);
    
    gd  = struct();
    for sub = 1:nSubclasses
        subclassNameFull    = subclasses(sub).Class;
        subclassName        = subsref(strsplit(subclassNameFull,'.'),struct('type','{}','subs',{{2}}));
        for dp = 1:nDataPools
            gd.(subclassName)(dp)  = eval(subclassNameFull);
            
            gd.(subclassName)(dp).data                  = dataPools(dp);
            gd.(subclassName)(dp).timeDeployment    	= datetime(2020,10,2,15,42,50);
            gd.(subclassName)(dp).timeOfInterestStart 	= datetime(2020,10,2,15,52,50);
            gd.(subclassName)(dp).timeOfInterestEnd 	= datetime(2020,10,2,19,32,38);
            gd.(subclassName)(dp).timeRecovery      	= datetime(2020,10,2,19,42,38);
            gd.(subclassName)(dp).cruise                = categorical({'M100'});
            gd.(subclassName)(dp).gear                  = [char(gd.(subclassName)(dp).gearType),'-',num2str(dp,'%02u')];
        end
    end    
    
    function dp = generateDataPools()
        % Dummy data    
        % Creates data pools with a single (s) or multiple (m),
        % independent (I) or dependent (D) variables.
        
        setNames    = {...
            'IsDs',...
            'ImDs',...
            'IsDm',...
            'ImDm'
            };
        dData(1)	= struct('IsDs',            struct('Variable',          {{'Time','Oxygen'}},...
                                                   'Data',              cat(2,linspace(0,3600,16000)',randn(16000,1)),...
                                                   'VariableOrigin',    {{datetime(2020,10,2,15,32,50),0}},...
                                                   'VariableType',      {{'Independent','Dependent'}}),...
                         'ImDs',            struct('Variable',          {{'Time','Depth','Oxygen'}},...
                                                   'Data',              cat(2,linspace(0,3600,16000)',reshape(repmat(0:15,1000,1),[],1),randn(16000,1)),...
                                                   'VariableOrigin',    {{datetime(2020,10,2,15,32,50),0,0}},...
                                                   'VariableType',      {{'Independent','Independent','Dependent'}}),...
                         'IsDm',            struct('Variable',          {{'Time','Nitrate','Oxygen'}},...
                                                   'Data',              cat(2,linspace(0,3600,16000)',randn(16000,1),randn(16000,1)),...
                                                   'VariableOrigin',    {{datetime(2020,10,2,15,32,50),0,0}},...
                                                   'VariableType',      {{'Independent','Dependent','Dependent'}}),...
                         'ImDm',            struct('Variable',          {{'Time','Depth','Nitrate','Oxygen'}},...
                                                   'Data',              cat(2,linspace(0,3600,16000)',reshape(repmat(0:15,1000,1),[],1),randn(16000,1),randn(16000,1)),...
                                                   'VariableOrigin',    {{datetime(2020,10,2,15,32,50),0,0,0}},...
                                                   'VariableType',      {{'Independent','Independent','Dependent','Dependent'}})...
                        );
        dData(2)	= struct('IsDs',            struct('Variable',          {{'Time','Oxygen'}},...
                                                   'Data',              cat(2,linspace(0,3600,31000)',randn(31000,1)),...
                                                   'VariableOrigin',    {{datetime(2020,10,2,15,32,50),0}},...
                                                   'VariableType',      {{'Independent','Dependent'}}),...
                         'ImDs',            struct('Variable',          {{'Time','Depth','Oxygen'}},...
                                                   'Data',              cat(2,linspace(0,3600,31000)',reshape(repmat(0:30,1000,1),[],1),randn(31000,1)),...
                                                   'VariableOrigin',    {{datetime(2020,10,2,15,32,50),0,0}},...
                                                   'VariableType',      {{'Independent','Independent','Dependent'}}),...
                         'IsDm',            struct('Variable',          {{'Time','Nitrate','Oxygen'}},...
                                                   'Data',              cat(2,linspace(0,3600,31000)',randn(31000,1),randn(31000,1)),...
                                                   'VariableOrigin',    {{datetime(2020,10,2,15,32,50),0,0}},...
                                                   'VariableType',      {{'Independent','Dependent','Dependent'}}),...
                         'ImDm',            struct('Variable',          {{'Time','Z','Nitrate','Oxygen'}},...
                                                   'Data',              cat(2,linspace(0,3600,31000)',reshape(repmat(0:30,1000,1),[],1),randn(31000,1),randn(31000,1)),...
                                                   'VariableOrigin',    {{datetime(2020,10,2,15,32,50),0,0,0}},...
                                                   'VariableType',      {{'Independent','Independent','Dependent','Dependent'}})...
                        );

        uniqueCombinations  = nchoosek(1:numel(setNames),2);
        nUniqueCombinations = size(uniqueCombinations,1);
        for ii = 1:nUniqueCombinations
            
            dp(ii)	= DataKit.dataPool();
            for jj = 1:numel(dData)
                nameOfSet	= setNames{uniqueCombinations(ii,jj)};

                dp(ii) 	= dp(ii).addVariable(dData(jj).(nameOfSet).Variable,dData(jj).(nameOfSet).Data,...
                            'VariableType',     dData(jj).(nameOfSet).VariableType,...
                            'VariableOrigin',   dData(jj).(nameOfSet).VariableOrigin);
            end
        end
    end    
end