function tbl = analyticalSamples()

    R = {'VariableNames',       'VariableUnits',        'VariableFormatSpec',   'VariableDescriptions', };
    C = { ...
        'Cruise',               '',                     '%C',                   'Cruise id.';...
        'Gear',                 '',                     '%C',                   'Gear id.';...
        'Subgear',              '',                     '%C',                   'Subgear id.';...
        'SampleId',             '',                     '%C',                   'Sample id.';...
        'ReplicateId',          '',                     '%C',                   'Replicate id.';...
        'MeasuringDeviceType',  '',                     '%C',                   'Measuring device type as defined in GearKit.measuringDeviceType.';...
        'Depth',                '',                     '%f',                   'Depth value';...
        'DepthReference',       '',                     '%C',                   'Depth reference (e.g. sediment surface)';...
        'DepthUnit',           	'',                     '%C',                   'Depth unit (e.g. m)';...
        'ParameterId',      	'',                     '%u16',                 'Parameter id as defined in DataKit.Metadata.variable.';...
        'Value',                '',                     '%f',                   'The value of the parameter. For value units, see the parameter definition.';...
        'QualityFlag',          '',                     '%u16',                 'Quality flag as defined in +DataKit/ressources/validQualityFlags.xlsx.';...
        'MethodId',             '',                     '%u16',                 'Method id as defined in +DataKit/ressources/validMethods.xlsx.';...
        'LabId',                '',                     '%u16',                 'Lab id as defined in +DataKit/ressources/validLabs.xlsx.' ...
    };
    tbl = cell2table(C',...
        'VariableNames',    C(:,1)',...
        'RowNames',         R);
end
