function tbl = gearDeployments()

    R = {'VariableNames',       'VariableUnits',        'VariableFormatSpec',   'VariableDescriptions', };
    C = { ...
        'Cruise',               '',                     '%C',                   'Cruise id.';...
        'Gear',                 '',                     '%C',                   'Gear id.';...
        'StationDepl',          '',                     '%C',                   'Deployment station number.';...
        'StationRec',           '',                     '%C',                   'Recovery station number.';...
        'DeplTime',             'UTC',                  '%D',                   'Deployment time.';...
        'RecTime',              'UTC',                  '%D',                   'Recovery time.';...
        'Lon',                  'decimal deg E',        '%f',                   'Longitude.';...
        'Lat',                  'decimal deg N',        '%f',                   'Latitude.';...
        'Depth',           	    'mbsl',                 '%f',                   'Waterdepth.';...
        'TransectID',      	    '',                     '%C',                   'Transect Id.';...
        'Comment',              '',                     '%s',                   ''...
    };
    tbl = cell2table(C',...
        'VariableNames',    C(:,1)',...
        'RowNames',         R);
end
