function tbl = gearRecovery()

    R = {'VariableNames',       'VariableUnits',        'VariableFormatSpec',   'VariableDescriptions', };
    C = { ...
        'Cruise',               '',                     '%C',                   'Cruise id.';...
        'Gear',                 '',                     '%C',                   'Gear id.';...
        'Subgear',              '',                     '%C',                   'Subgear id.';...
        'ChSedRec',             '',                     '%L',                   'true = chamber retained all sediment.';...
        'ChClosed',             '',                     '%L',                   'true = chamber retained all water.';...
        'ChH1',                 'cm',                   '%f',                   'Chamber height 1.';...
        'ChH2',                 'cm',                   '%f',                   'Chamber height 2.';...
        'ChH3',                 'cm',                   '%f',                   'Chamber height 3.';...
        'ChH4',                 'cm',                   '%f',                   'Chamber height 4.';...
        'ChH5',                 'cm',                   '%f',                   'Chamber height 5.';...
        'ChHSZ',                'cm',                   '%f',                   'Chamber Schleppzeiger.';...
        'ChDia',                'cm',                   '%f',                   'Chamber diameter.';...
        'ImageStart',           'cm',                   '%f',                   'Start index of chamber images.';...
        'ImageEnd',             'cm',                   '%f',                   'End index of chamber images.';...
        'Sampling',             '',                     '%s',                   'Sampling comments.';...
        'CommentsTech',         '',                     '%s',                   'Technical comments.';...
        'Comments',             '',                     '%s',                   'From the recovery protocol.'...
    };
    tbl = cell2table(C',...
        'VariableNames',    C(:,1)',...
        'RowNames',         R);
end
