function tbl = measuringDevicesConfiguration()

    R = {'VariableNames',       'VariableUnits',        'VariableFormatSpec',   'VariableDescriptions', };
    C = { ...
        'Cruise',               '',                     '%C',                   'Cruise id.';...
        'Gear',                 '',                     '%C',                   'Gear id.';...
        'Type',                 '',                     '%C',                   'Measuring device type. As defined in GearKit.measuringDeviceType.';...
        'SerialNumber',         '',                     '%C',                   'The serial number of the measuring device.';...
        'Variable',             '',                     '%u16',                 'The variable reported by the measuring device. As defined in DataKit.Metadata.variable.';...
        'TypeNew',              '',                     '%C',                   'The new measuring device Type. As defined in GearKit.measuringDeviceType.';...
        'SerialNumberNew',      '',                     '%C',                   'The new serial number.';...
    };
    tbl = cell2table(C',...
        'VariableNames',    C(:,1)',...
        'RowNames',         R);
end
