function tbl = measuringDevices()

    R = {'VariableNames',       'VariableUnits',        'VariableFormatSpec',   'VariableDescriptions', };
    C = { ...
        'Cruise',               '',                     '%C',                   'Cruise id.';...
        'Gear',                 '',                     '%C',                   'Gear id.';...
        'Type',                 '',                     '%C',                   'Measuring device type. As defined in GearKit.measuringDeviceType.';...
        'SerialNumber',         '',                     '%C',                   'The serial number of the measuring device.';...
        'MountingLocation',     '',                     '%s',                   'The mounting location on the gear.';...
        'DeviceDomain',         '',                     '%C',                   'Device domain. As defined in GearKit.deviceDomain.';...
        'WorldDomain',          '',                     '%C',                   'World domain. As defined in GearKit.worldDomain.';...
        'Comment',              '',                     '%s',                   'Comments.'...
    };
    tbl = cell2table(C',...
        'VariableNames',    C(:,1)',...
        'RowNames',         R);
end
