function tbl = winklerTitration()

    R = {'VariableNames',       'VariableUnits',        'VariableFormatSpec',   'VariableDescriptions', };
    C = { ...
        'Cruise',               '',                     '%C',                   'Cruise id.';...
        'Station',              '',                     '%C',                   'Station id.';...
        'Gear',                 '',                     '%C',                   'Gear id.';...
        'Subgear',              '',                     '%C',                   'Subgear id.';...
        'SampleID',             '',                     '%C',                   'Sample id.';...
        'Date',                 'UTC',                  '%D',                   'Date of measurement.';...
        'FlaskNumber',          '',                     '%u16',                 'Winkler flask number.';...
        'FlaskVolume',          'mL',                   '%f',                   'Winkler flask volume.';...
        'TitrationVolume',      'mL',                   '%f',                   'Volume of the added Na-thiosulfate solution.';...
        'VolumeReagent1',       'mL',                   '%f',                   'Volume of MnCl2 added.';...
        'VolumeReagent2',       'mL',                   '%f',                   'Volume of KI-KOH added.';...
        'TitrandConcentation',  'mol/L',                '%f',                   'Concentration of the added Na-thiosulfate solution.';...
        'TiterFactor',          '',                     '%f',                   'Titration correction factor.';...
        'Oxygen',               'µM',                   '%f',                   'Oxygen concentration.';...
        'Comment',              '',                     '%s',                   'From the recovery protocol.'...
    };
    tbl = cell2table(C',...
        'VariableNames',    C(:,1)',...
        'RowNames',         R);
end
