function obj = fit(obj,varargin)
% FIT

    fitObj      = cell(obj.nFits,1);
    fitGOF      = cell(obj.nFits,1);
    fitOutput   = cell(obj.nFits,1);
    for ff = 1:obj.nFits
        switch obj.fitType
            case 'linear'
                fitType  	= fittype('k*t + Coff',...
                                'dependent',        'C',...
                                'independent',		't');
                fitOptions	= fitoptions(...
                                'Method',			'NonlinearLeastSquares',...
                                'StartPoint',		[rand(1)	rand(1)	],...
                                'Lower',			[-inf      -inf     ],...
                                'Upper',			[ inf       inf     ],...
                                'Display',			'off',...
                                'Normalize',        'off',...
                                'Exclude',          obj.excluded{obj.indSource(ff),obj.indParameter(ff)});
            case 'sigmoidal'
                error('Dingi:AnalysisKit:bigoFluxAnalysis:fit:notImplementedYet',...
                'Not fully implemented yet.')

                fitType  	= fittype('Cmax/(1 + exp(-k*(t - t0))) + Coff',...
                                'dependent',        'C',...
                                'independent',		't');
                LM = 2e3;
                FitLimits   = [ LM          LM      NaN     LM    	; ...   % upper limit
                                rand(1)     rand(1)	NaN     rand(1)	; ...   % start points
                                0          -LM      NaN    -LM     	];      % lower limit


                fitOptions	= fitoptions(...
                                'Method',			'NonlinearLeastSquares',...
                                'Upper',			FitLimits(1,:),...
                                'StartPoint',		FitLimits(2,:),...
                                'Lower',			FitLimits(3,:),...
                                'Display',			'off',...
                                'Normalize',        'off',...
                                'Exclude',          ExcludeMask);
            otherwise
                error('Dingi:AnalysisKit:bigoFluxAnalysis:fit:unknownFitType',...
                    'The fit type ''%s'' is not defined yet.',obj.fitType)
        end
        XData   = obj.timeRaw{obj.indSource(ff)};
        YData   = obj.fluxParameterRaw{obj.indSource(ff),obj.indParameter(ff)};



        [fitObj{ff},fitGOF{ff},fitOutput{ff}] = fit(XData,YData,fitType,fitOptions);
    end

    obj.fitObjects  = fitObj;
    obj.fitGOF      = fitGOF;
    obj.fitOutput   = fitOutput;
end
